* Auto Html
  Generating html and css files according to a given templete. Mainly used to create static html files and its layout.
** similar tools
   - an online layout generator: http://www.pagecolumn.com/
** Implementation
*** low level function
    1. add child element
       #+begin_src c
       HtmlElement add_child(HtmlElement parent, HtmlElement child, Position pos)
       #+end_src
       一个parent element最多被划分为两格，不论在水平还是垂直方向。 这是最简单的情况，复杂的情况都可以通过这个实现。
       
       先不考虑复杂的实现，pos指定 方向，如果为水平，则再指定靠左还是靠右，如不指定，则排在之前的child后。
       #+begin_src c
       struct Position {
         int oritation; //水平还是垂直
         int leftp; //靠在最左
         int rightp;
         int topp;
         int bottomp;
       }
       #+end_src

       生成复杂的网格，都可以基于这个函数了。这个就是递归的基本情况。

** todo
*** DONE add parent paremeter to HtmlElement
    CLOSED: [2016-05-10 Tue 21:26]
    - State "DONE"       from "TODO"       [2016-05-10 Tue 21:26]
*** DONE fix inline-block margin problem
    CLOSED: [2016-05-16 Mon 14:20]
    - State "DONE"       from "TODO"       [2016-05-16 Mon 14:20] \\
      Using absolute position instead.
*** TODO add more style at a time
    Support both parameter:
    #+begin_src perl
    # 1.
    $e->style("width", "100px");
    # 2.
    $e->style({width=>"100px",height=>"200px"});
    #+end_src

** Ideas
*** 模板中支持原生HTML作为一个element的内容。
    这样便改变了编写html文件的方式。用户不用过多的关注太多的html的细节。
** HTML & CSS knowledge
*** element align
    通用思路：使用padding，达到设置的目的。
    
    1. horizonally align any elements in a div
       Just use 'text-align'.
       | value  | function                       |
       |--------+--------------------------------|
       | left   | element align to left(default) |
       | center | align to center                |
       | right  | align to right                 |
    2. vertically align in a div
       - centering single line of text element
         Set 'line-height' to div's 'height'.
       - Other cases, to be added.

** how to run
   just ./run.sh
